"""Code-as-action: the ``invoke`` tool (v1 probe surface).

Mirrors ``process.py:bash`` for the execution machinery — same subprocess
pattern, process-group kill, ``CancelledError`` handling, and repo-lock
heuristic — so v1 holds *trust parity with bash* (the harness's existing
deliberate security-boundary decision; hard sandboxing is a later, config-gated
hardening per the code-as-action investigation, proposal §1/§4).

Difference from ``bash``: the action is a Python snippet, and the snippet runs
with a generated ``harness_tools`` RPC bridge on a private socket. Every
harness-tool call the code makes (``read``/``grep``/``delegate``/``ask``/
``converse``/``post``/...) is executed by the parent through
``ToolRegistry.execute()`` — **policy parity by construction** (sandbox roots,
role allow-lists, spawn caps, comms routing, budget lines all apply). Only
what the snippet prints (plus a ``# result:`` footer listing snapshot handles)
enters the agent's context; tool payloads stay in-process and are snapshotted
so the model can page them via ``result_read``.

Terminal intent from inside the sandbox is expressed by *printing a marker*
(``# TERMINAL:report:...``), which the harness loop recognizes and delivers —
the terminal contract stays enforced, and the sandboxed code never invokes the
terminal tools directly.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import socket
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

from ...config import InvokeConfig
from ..task import ReportPayload
from .process import _kill_process_group
from .registry import ToolDef

if TYPE_CHECKING:
    from ..tool_context import ToolContext


TOOL_INVOKE_DEF = ToolDef(
    name="invoke",
    description=(
        "Execute a Python code snippet and return what it prints. This is the "
        "code-as-action tool: write logic as code instead of shell (batch file "
        "transforms, parsing, generating structured output, gluing many small "
        "steps into one call). The snippet runs in a fresh `python3` process "
        "in the working directory, with the injected `harness_tools` module on "
        "the path — `from harness_tools import read, grep, write, delegate, "
        "ask, converse, plan, checkpoint, usage, status, ...` gives the code "
        "the SAME tools you have, with the SAME policies enforced, but without "
        "polluting context: only what the code PRINTS enters context, and each "
        "tool payload is snapshotted behind a result_id for paging via "
        "result_read. To deliver a result, either finish and then call the "
        "report tool, or print a terminal marker (e.g. "
        "`print(harness_tools.report('summary'))`). WARNING: arbitrary Python "
        "runs WITHOUT a sandbox and can read/write the host filesystem, access "
        "the network, and run as the invoking user — same deliberate security "
        "boundary as the bash tool."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "code": {
                "type": "string",
                "description": "Python source to execute. Runs via `python3 -` fed "
                               "over stdin; harness_tools is importable for harness "
                               "tool access. Do not paste fetched/read content "
                               "verbatim into code (code-not-data).",
            },
            "timeout": {
                "type": "integer",
                "description": "Timeout in milliseconds (default from config `invoke.timeout_ms`, 60000)",
            },
            "workdir": {
                "type": "string",
                "description": "Working directory to run the snippet in (default is the sandbox/generated root)",
            },
        },
        "required": ["code"],
    },
)


# ---------------------------------------------------------------------------
# harness_tools RPC stub — injected into the subprocess. The snippet imports it
# by name; each call is a JSON-lines request on a private socketpair, serviced
# by _serve_harness_tools through ToolRegistry.execute().
# ---------------------------------------------------------------------------

_STUB_SOURCE = """\
# Generated by dynamic_harness (core/tools/code.py) for a sandboxed invoke().
# DO NOT EDIT.
\"\"\"harness_tools - RPC bridge from an `invoke` run back to the harness.

Only what your code PRINTS (plus the `# result:` footer the harness appends)
enters the agent's context; tool payloads stay in-process with you and are
snapshotted so the model can page them via result_read later. Terminal intent
is expressed by PRINTING a marker:

    print(harness_tools.report("summarized the widget lifecycle"))
    print(harness_tools.fail("blocked: API key missing"))
    print(harness_tools.escalate("needs a human decision", context={"x": 1}))

recursive invoke / bash / result paging / terminal tools are not available
through this bridge - they are agent-level.
\"\"\"
import json
import os
import socket

__all__ = [
    "read", "write", "glob", "grep", "edit", "webfetch",
    "delegate", "ask", "converse", "kill", "status", "resume",
    "read_artifact", "plan", "checkpoint", "usage", "archive",
    "post", "channel_read", "channels", "channel_info",
    "subscribe", "unsubscribe", "message", "skill_load",
    "report", "escalate", "fail",
]


class HarnessToolsError(RuntimeError):
    \"\"\"Raised when the harness-side tool call fails or the channel closed.\"\"\"


def _connect():
    fd = int(os.environ.get("HARNESS_TOOLS_FD", "-1"))
    if fd < 0:
        raise HarnessToolsError(
            "harness_tools is only importable inside a dynamic_harness "
            "invoke() subprocess (HARNESS_TOOLS_FD env var missing)."
        )
    sock = socket.fromfd(fd, socket.AF_UNIX, socket.SOCK_STREAM)
    os.close(fd)
    return sock.makefile("r", encoding="utf-8"), sock.makefile("w", encoding="utf-8")


_reader, _writer = _connect()
_counter = {"n": 0}
last_result_id = None


def _call(name, **kwargs):
    global last_result_id
    _counter["n"] += 1
    req = {"id": _counter["n"], "name": name, "arguments": kwargs}
    _writer.write(json.dumps(req) + "\\n")
    _writer.flush()
    line = _reader.readline()
    if not line:
        raise HarnessToolsError("harness_tools channel closed by the harness")
    resp = json.loads(line)
    last_result_id = resp.get("result_id")
    if resp.get("error"):
        raise HarnessToolsError(resp["error"])
    return resp.get("content", "")


def _marker(kind, payload):
    return "# TERMINAL:" + kind + ":" + json.dumps(payload)


# -- hamess access ---------------------------------------------------------

def read(path, token_limit=100, token_offset=0):
    return _call("read", path=path, token_limit=token_limit, token_offset=token_offset)


def write(path, content):
    return _call("write", path=path, content=content)


def glob(pattern):
    return _call("glob", pattern=pattern)


def grep(pattern, include=None, path=None):
    return _call("grep", pattern=pattern, include=include, path=path)


def edit(path, old_string, new_string):
    return _call("edit", path=path, old_string=old_string, new_string=new_string)


def webfetch(url):
    return _call("webfetch", url=url)


def delegate(description, role=None, system_prompt=None, agent_type=None,
             intent=None, end_state=None, constraints=None, authority=None):
    return _call("delegate", description=description, role=role,
                 system_prompt=system_prompt, agent_type=agent_type,
                 intent=intent, end_state=end_state, constraints=constraints,
                 authority=authority)


def ask(question):
    return _call("ask", question=question)


def converse(agent_id, message):
    return _call("converse", agent_id=agent_id, message=message)


def kill(agent_id, reason=None, recursive=False):
    return _call("kill", agent_id=agent_id, reason=reason, recursive=recursive)


def status(agent_id=None):
    return _call("status", agent_id=agent_id)


def resume(agent_id, note=None, strategy="automatic"):
    return _call("resume", agent_id=agent_id, note=note, strategy=strategy)


def read_artifact(artifact_id, file=None, level="auto"):
    return _call("read_artifact", artifact_id=artifact_id, file=file, level=level)


def plan(steps, objective=None, acceptance=None, deliverable=None):
    return _call("plan", steps=steps, objective=objective,
                 acceptance=acceptance, deliverable=deliverable)


def checkpoint(note, done=None):
    return _call("checkpoint", note=note, done=done)


def usage():
    return _call("usage")


def archive(path=None, content=None, label=None, summary=None):
    return _call("archive", path=path, content=content, label=label, summary=summary)


def post(topic, content, kind="notification", stage="final"):
    return _call("post", topic=topic, content=content, kind=kind, stage=stage)


def channel_read(topic):
    return _call("channel_read", topic=topic)


def channels():
    return _call("channels")


def channel_info(topic):
    return _call("channel_info", topic=topic)


def subscribe(topic):
    return _call("subscribe", topic=topic)


def unsubscribe(topic):
    return _call("unsubscribe", topic=topic)


def message(agent_id, content, kind="instruction"):
    return _call("message", agent_id=agent_id, content=content, kind=kind)


def skill_load(skill):
    return _call("skill_load", skill=skill)


# -- terminal markers (delivered by the harness loop, never called directly) --

def report(summary, technical_summary=None, full_report=None, confidence=None,
           artifact_ids=None, files_written=None):
    return _marker("report", {
        "summary": summary, "technical_summary": technical_summary,
        "full_report": full_report, "confidence": confidence,
        "artifact_ids": artifact_ids or [], "files_written": files_written or [],
    })


def escalate(issue, **context):
    payload = dict(context)
    payload["issue"] = issue
    return _marker("escalate", payload)


def fail(error, trace=None):
    return _marker("fail", {"error": error, "trace": trace})
""".strip()


# ---------------------------------------------------------------------------
# Parent side: RPC service loop + terminal-marker handling
# ---------------------------------------------------------------------------

#: Tools the sandbox may not reach through the bridge: recursive invoke,
#: bash/result paging (agent-level execution), and the terminal tools (their
#: intent is expressed via printed markers instead).
_BLOCKED_RPC_TOOLS: frozenset[str] = frozenset({
    "invoke", "bash", "result_read", "result_bash",
    "report", "escalate", "fail",
})

_BLOCKED_RPC_MESSAGE = (
    "Error: tool '{name}' is not available inside invoke — the terminal "
    "tools (report/escalate/fail) are expressed by printing the # TERMINAL: "
    "marker (harness_tools.report/...), and invoke/bash/result paging are "
    "agent-level tools."
)

_TERMINAL_RE = re.compile(r"^# TERMINAL:(report|escalate|fail):(.*)$", re.MULTILINE)


async def _serve_harness_tools(
    sock: socket.socket, ctx: "ToolContext", result_ids: list[str]
) -> None:
    """Service JSON-lines requests from a sandboxed ``invoke`` subprocess.

    Each request is forwarded through ``ToolRegistry.execute()`` so the exact
    policies that govern the direct tools (role allow-list, sandbox roots,
    spawn caps, comms routing, budget lines) apply to the code-driven call.
    Runs as a task alongside ``proc.communicate``; exits on socket EOF.
    """
    reader, writer = await asyncio.open_connection(sock=sock)
    try:
        while True:
            line = await reader.readline()
            if not line:
                break
            try:
                req = json.loads(line)
            except json.JSONDecodeError:
                continue
            rid = req.get("id", 0)
            name = str(req.get("name", ""))
            args = dict(req.get("arguments") or {})
            result_id = None
            if name in _BLOCKED_RPC_TOOLS:
                content = _BLOCKED_RPC_MESSAGE.format(name=name)
            else:
                try:
                    # token_limit huge: the CODE needs the full payload in-process
                    # (lean-context is achieved by the invoke footer + what the
                    # snippet prints, not by slicing the bridge's answers).
                    # Strip any pagination knobs the stub mirrored from the tool
                    # signature so they cannot collide with the outer override.
                    args.pop("token_limit", None)
                    args.pop("token_offset", None)
                    result = await ctx.tool_registry.execute(
                        name, f"invoke-{rid}", agent=ctx,
                        token_limit=10**6, **args,
                    )
                    content = result.content or ""
                    result_id = getattr(result, "result_id", None)
                    if result_id:
                        result_ids.append(result_id)
                except Exception as exc:  # noqa: BLE001
                    content = f"Error executing {name}: {exc}"
            writer.write(
                json.dumps({"id": rid, "content": content, "result_id": result_id}).encode()
                + b"\n"
            )
            await writer.drain()
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:  # noqa: BLE001
            pass


def _handle_terminal_markers(text: str, ctx: "ToolContext") -> tuple[str, bool]:
    """Scan ``invoke`` output for ``# TERMINAL:<name>:<json>`` markers and
    deliver the FIRST one through the agent's terminal path.

    The marker line is replaced with a ``[terminal: ...]`` note so the model's
    context stays clean. Returns ``(text, delivered)``.
    """
    m = _TERMINAL_RE.search(text)
    if not m:
        return text, False
    name, raw = m.group(1), m.group(2)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return text, False
    note = {
        "report": "[terminal: report delivered]",
        "escalate": "[terminal: escalated]",
        "fail": "[terminal: failed]",
    }[name]
    text = text[: m.start()] + note + text[m.end():]
    try:
        if name == "report":
            ctx.report(ReportPayload(
                task_id=ctx.task_id,
                summary=str(payload.get("summary", "")),
                technical_summary=payload.get("technical_summary"),
                full_report=payload.get("full_report"),
                confidence=payload.get("confidence"),
                artifact_ids=list(payload.get("artifact_ids") or []),
                files_written=list(payload.get("files_written") or []),
            ))
        elif name == "escalate":
            ctx.escalate(
                str(payload.get("issue", "")),
                **{k: v for k, v in payload.items() if k != "issue"},
            )
        else:
            ctx.fail(str(payload.get("error", "")), trace=payload.get("trace"))
    except Exception:  # noqa: BLE001 — never crash the tool over a bad payload
        return text, False
    return text, True


# ---------------------------------------------------------------------------
# Import allowlist (v1 discipline knob; default off = parity with bash)
# ---------------------------------------------------------------------------

_IMPORT_RE = re.compile(
    r"^\s*(?:import|from)\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)",
    re.MULTILINE,
)


def _disallowed_imports(code: str, allowlist: list[str]) -> list[str]:
    """Top-level modules imported by ``code`` that are not in ``allowlist``."""
    allowed = {m.split(".")[0] for m in allowlist}
    seen: set[str] = set()
    banned: list[str] = []
    for match in _IMPORT_RE.finditer(code or ""):
        root = match.group(1).split(".")[0]
        if root in seen or root in allowed:
            continue
        seen.add(root)
        banned.append(root)
    return sorted(banned)


#: Heuristic mutation detection for the repo lock (mirrors bash's read-only
#: classification in spirit: a clearly read/compute-only snippet skips the
#: lock; anything that plausibly writes takes it). Conservative — false
#: positives only cost a short serialization, never a corrupted workspace.
_MUTATION_RE = re.compile(
    r"\.write_text\(|\.write_bytes\(|\.open\(|open\(|"
    r"os\.(?:remove|unlink|rename|rmdir|makedirs|mkdir|symlink|replace|system|popen)|"
    r"shutil\.|subprocess|\.mkdir\(|\.rmdir\(|\.unlink\(|\.touch\(|"
    r"\.move\(|\.copy\(|\.rename\(|Path\([^)]*\)\.write"
)


def _looks_mutating(code: str) -> bool:
    return bool(_MUTATION_RE.search(code or ""))


def _cap_text(text: str, cap: int, label: str) -> str:
    """Slice ``text`` to ``cap`` bytes with a truncation note (v1 config knob;
    default None = uncapped, parity with bash: full output is retained and
    paged via result_read)."""
    if len(text) <= cap:
        return text
    return (
        text[:cap]
        + f"\n[{label} truncated at {cap} bytes — bytes beyond are NOT retained; "
        "re-run invoke with a narrower scope to see more]"
    )


# ---------------------------------------------------------------------------
# The tool
# ---------------------------------------------------------------------------


async def invoke(
    *, ctx: "ToolContext", code: str, timeout: int | None = None,
    workdir: str | None = None,
) -> str:
    """Execute a Python snippet with the ``harness_tools`` RPC bridge available.

    Trust parity with ``bash``: subprocess execution, process-group kill on
    timeout/cancel, cwd default = generated root, and a mutation heuristic for
    the repo lock. The snippet's harness-tool calls route through the runtime's
    ToolRegistry (policy parity by construction); only printed output enters
    context, terminal intent arrives via ``# TERMINAL:`` markers.
    """
    cfg: InvokeConfig = (ctx.config.invoke if ctx.config else None) or InvokeConfig()
    timeout_ms = int(timeout) if timeout is not None else cfg.timeout_ms

    code = code or ""
    if not code.strip():
        return "(no-op) empty code snippet"

    allowlist = list(cfg.import_allowlist or [])
    if allowlist:
        banned = _disallowed_imports(code, allowlist)
        if banned:
            return (
                "Error: invoke refused — the code imports modules outside the "
                f"configured import_allowlist: {', '.join(banned)}. Nothing was "
                "executed. Rewrite the snippet with only allowed imports or ask "
                "the operator to extend invoke.import_allowlist."
            )

    cwd = Path(workdir) if workdir else ctx.generated_root
    repo_lock = None
    if _looks_mutating(code):
        repo_lock = ctx.repo_lock()
        await repo_lock.acquire()

    result_ids: list[str] = []
    proc = None
    parent_sock, child_sock = socket.socketpair()
    parent_sock.setblocking(False)
    reader_task = asyncio.create_task(_serve_harness_tools(parent_sock, ctx, result_ids))
    try:
        with tempfile.TemporaryDirectory(prefix="harness_tools_") as td:
            stub_path = Path(td) / "harness_tools.py"
            stub_path.write_text(_STUB_SOURCE, encoding="utf-8")
            env = dict(os.environ)
            env["HARNESS_TOOLS"] = str(stub_path)
            env["HARNESS_TOOLS_FD"] = str(child_sock.fileno())
            env["PYTHONPATH"] = td + os.pathsep + env.get("PYTHONPATH", "")
            proc = await asyncio.create_subprocess_exec(
                "python3", "-u", "-",
                stdin=asyncio.subprocess.PIPE,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=cwd,
                start_new_session=True,
                pass_fds=(child_sock.fileno(),),
                env=env,
            )
            try:
                stdout, stderr = await asyncio.wait_for(
                    proc.communicate(code.encode()), timeout=timeout_ms / 1000
                )
            except asyncio.TimeoutError:
                await _kill_process_group(proc)
                return (
                    f"Error: invoke timed out after {timeout_ms}ms (the whole "
                    "process group was killed). Pass a larger 'timeout' (ms) "
                    "parameter, or narrow the snippet."
                )
            except asyncio.CancelledError:
                # Agent cancelled (kill/resume/reset) mid-snippet: take the
                # process group down before re-raising so no subprocess (or
                # spawned grandchild) is orphaned.
                await _kill_process_group(proc)
                raise
    finally:
        child_sock.close()
        parent_sock.close()
        reader_task.cancel()
        if repo_lock:
            repo_lock.release()

    out_text = stdout.decode(errors="replace") if stdout else ""
    err_text = stderr.decode(errors="replace") if stderr else ""
    out_text = _cap_text(out_text, cfg.stdout_cap, "stdout") if cfg.stdout_cap else out_text
    err_text = _cap_text(err_text, cfg.stderr_cap, "stderr") if cfg.stderr_cap else err_text

    result = out_text
    if err_text:
        result += f"\n(STDERR)\n{err_text}"
    result, _ = _handle_terminal_markers(result, ctx)
    if result_ids:
        # Dedupe while preserving order: the same snapshot may be referenced by
        # several bridge calls (e.g. read twice served from one snapshot).
        seen: set[str] = set()
        ids = [rid for rid in result_ids if not (rid in seen or seen.add(rid))]
        result += "\n# result: " + " ".join(ids)
    return result.strip() or "(no output)"