from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from datetime import datetime
    from pathlib import Path
    from typing import Sequence

    from ..artifact.store import Artifact
    from ..memory.repository import Commit
    from .task import ActivityEvent, BudgetRequest, Escalation, Failure, ReportPayload, Task
    from ..llm.provider import LLMProvider


class LLMProviderProto(Protocol):
    async def generate(self, system: str, user: str) -> object: ...

    async def generate_with_tools(
        self, messages: list[dict], tools: list[dict]
    ) -> object: ...

    async def generate_structured(
        self, system: str, user: str, response_model: type
    ) -> object: ...

    async def aclose(self) -> None: ...


class ArtifactStoreProto(Protocol):
    def save(self, artifact: Artifact) -> None: ...

    def get(self, artifact_id: str) -> Artifact | None: ...

    def write_text(self, artifact_id: str, name: str, content: str) -> Path: ...

    def read_text(self, artifact_id: str, name: str) -> str | None: ...

    def list_files(self, artifact_id: str) -> Sequence[Path]: ...

    def clear(self) -> None: ...


class RepositoryProto(Protocol):
    def commit(self, commit: Commit) -> Commit: ...

    def get(self, commit_id: str) -> Commit | None: ...

    def log(self, limit: int = 50) -> Sequence[Commit]: ...

    def tree(self, root_id: str | None = None) -> dict[str, list[str]]: ...

    def count(self) -> int: ...

    def clear(self) -> None: ...


class EventBusProto(Protocol):
    def emit_activity(self, event: ActivityEvent) -> None: ...

    def emit_report(self, agent_id: str, payload: ReportPayload) -> None: ...

    def emit_budget_request(self, agent_id: str, req: BudgetRequest) -> None: ...

    def emit_escalation(self, agent_id: str, esc: Escalation) -> None: ...

    def emit_failure(self, agent_id: str, fail: Failure) -> None: ...

    def on_activity(self, handler) -> None: ...

    def on_report(self, handler) -> None: ...

    def on_budget_request(self, handler) -> None: ...

    def on_escalation(self, handler) -> None: ...

    def on_failure(self, handler) -> None: ...

    def clear(self) -> None: ...


class UsageTrackerProto(Protocol):
    async def record_usage(
        self, agent_id: str, *, prompt_tokens: int = 0,
        completion_tokens: int = 0, message_count: int = 0
    ) -> None: ...

    def get_usage(self, agent_id: str) -> dict: ...

    def total_usage(self) -> dict: ...

    def clear(self) -> None: ...
